# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: PR Checks

permissions:
  contents: write
  pull-requests: write
  
on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop ]
  
jobs:
  build-test:
    name: Build, Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: [9.0.x]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Restore
        run: dotnet restore

      - name: Formatting
        run: dotnet format --verify-no-changes

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage" --results-directory coverage

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate GitHub Markdown Summary
        run: |
          reportgenerator -reports:"coverage/**/coverage.cobertura.xml" -targetdir:"coverage-report" -reporttypes:"MarkdownSummaryGithub"
      
      - name: Upload Coverage Summary
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}
          path: coverage-report/SummaryGithub.md

  

  post-comment:
    name: Post Coverage Comment
    needs: build-test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: Download all coverage summaries
        uses: actions/download-artifact@v4
        with:
          path: summaries

      - name: Merge Markdown summaries
        run: |
          echo "# Coverage Report" > final.md
          echo "" >> final.md

          for f in summaries/**/SummaryGithub.md; do
            echo "## $(basename $(dirname $f))" >> final.md
            echo "" >> final.md
            cat "$f" >> final.md
            echo "" >> final.md
          done

      - name: Comment Coverage Report on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('final.md', 'utf8');
            const pr = context.payload.pull_request.number;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              body
            });
